# -*- coding: utf-8 -*-
"""sentiment_analyser.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OYoNJ4VgBIZUvT_ShKC-lseKUqNVQhOi
"""

from google.colab import files
files.upload()

!pip install kaggle --quiet

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

from google.colab import files
files.upload()

import zipfile

zip_path = "/content/archive (1).zip"
extract_path = "/content/twitter_data"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print("Extraction complete!")

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from wordcloud import WordCloud

train_df = pd.read_csv("/content/twitter_data/twitter_training.csv", header=None)
valid_df = pd.read_csv("/content/twitter_data/twitter_validation.csv", header=None)

df = pd.concat([train_df, valid_df], ignore_index=True)
df.columns = ['ID', 'Entity', 'Sentiment', 'Tweet']

df.dropna(inplace=True)
print("Dataset loaded and cleaned!")
print("Shape:", df.shape)
print("Sentiment counts:\n", df['Sentiment'].value_counts())
display(df.head())

# Sentiment distribution
plt.figure(figsize=(6,4))
sns.countplot(x='Sentiment', data=df, palette='Set2')
plt.title('Sentiment Distribution')
plt.xlabel('Sentiment')
plt.ylabel('Tweet Count')
plt.show()

# Top 10 Entities with Sentiment Breakdown
plt.figure(figsize=(12,6))
sns.countplot(y='Entity', hue='Sentiment', data=df,
              order=df['Entity'].value_counts().index[:10], palette='coolwarm')
plt.title('Top 10 Entities - Sentiment Breakdown')
plt.xlabel('Tweet Count')
plt.ylabel('Entity')
plt.legend(title='Sentiment')
plt.show()

# Word Cloud - Positive Sentiment
positive_text = " ".join(df[df['Sentiment'] == 'Positive']['Tweet'])

plt.figure(figsize=(10,5))
wordcloud_pos = WordCloud(width=800, height=400, background_color='white').generate(positive_text)
plt.imshow(wordcloud_pos, interpolation='bilinear')
plt.axis('off')
plt.title('Word Cloud - Positive Sentiment')
plt.show()

# Word Cloud - Negative Sentiment
negative_text = " ".join(df[df['Sentiment'] == 'Negative']['Tweet'])

plt.figure(figsize=(10,5))
wordcloud_neg = WordCloud(width=800, height=400, background_color='black').generate(negative_text)
plt.imshow(wordcloud_neg, interpolation='bilinear')
plt.axis('off')
plt.title('Word Cloud - Negative Sentiment')
plt.show()